### ISSUE TITLE
Support for Sphinx 1.3+?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-helpers#218]
Are there plans to support Sphinx 1.3+ here? We just upgraded Sphinx on our servers but then we got this error below (RHEL6, Python 2.7). I am aware of 4383d1559a4f but at least is there a workaround if not a fix? It does not make sense for us to lock into an older version of Sphinx just for this, since we are not even building doc for Astropy on our server.

```
+++ python setup.py build
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
  File ".../astropy/astropy/ah_bootstrap.py", line 921, in <module>
    BOOTSTRAPPER = _Bootstrapper.main()
  File ".../astropy/astropy/ah_bootstrap.py", line 217, in main
    bootstrapper.run()
  File ".../astropy/astropy/ah_bootstrap.py", line 303, in run
    dist = method()
  File ".../astropy/astropy/ah_bootstrap.py", line 361, in get_local_directory_dist
    dist = self._directory_import()
  File ".../astropy/astropy/ah_bootstrap.py", line 458, in _directory_import
    ['egg_info'])
  File ".../setuptools/sandbox.py", line 242, in run_setup
    raise
  File ".../contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../setuptools/sandbox.py", line 195, in setup_context
    yield
  File ".../contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File ".../setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File ".../setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File ".../setuptools/sandbox.py", line 195, in setup_context
    yield
  File ".../setuptools/sandbox.py", line 239, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File ".../setuptools/sandbox.py", line 269, in run
    return func()
  File ".../setuptools/sandbox.py", line 238, in runner
    _execfile(setup_script, ns)
  File ".../setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File ".../astropy/astropy_helpers/setup.py", line 20, in <module>
    cmdclass = register_commands(NAME, VERSION, RELEASE)
  File ".../astropy/astropy_helpers/astropy_helpers/setup_helpers.py", line 142, in register_commands
    from .commands.build_sphinx import AstropyBuildSphinx, AstropyBuildDocs
  File ".../astropy/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 16, in <module>
    from sphinx.setup_command import BuildDoc as SphinxBuildDoc
  File ".../sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File ".../sphinx/application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File ".../sphinx/builders/__init__.py", line 22, in <module>
    from sphinx.util import i18n, path_stabilize
  File ".../sphinx/util/i18n.py", line 16, in <module>
    from babel.messages.pofile import read_po
ImportError: No module named babel.messages.pofile
```

**Comment by pllim** [comment]
Ops. Looks like this is a duplicate of astropy/astropy#3698.
