### ISSUE TITLE
Sphinx 1.6.1 fails in building package based on astropy_helpers

### ISSUE THREAD

**Issue by cczhu** [astropy/astropy-helpers#301]
Things work well for sphinx 1.5.6, which is currently used on travis, but locally with sphinx 1.6.1, it fails with the following error (we  -- @mhvk and I -- have not yet tried to reproduce this for astropy itself):

```Traceback (most recent call last):
  File "<stdin>", line 36, in <module>
  File "/home/cczhu/pythonenv/ml3/lib/python3.5/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/home/cczhu/pythonenv/ml3/lib/python3.5/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/home/cczhu/pythonenv/ml3/lib/python3.5/site-packages/sphinx/application.py", line 488, in emit
    return self.events.emit(event, self, *args)
  File "/home/cczhu/pythonenv/ml3/lib/python3.5/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/cczhu/GitHub/baseband/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 252, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/cczhu/GitHub/baseband/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 311, in automodsumm_to_autosummary_lines
    if 'astropy_helpers.sphinx.ext.automodapi' in app._extensions:
AttributeError: 'Sphinx' object has no attribute '_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 42, in <module>
NameError: name 'self' is not defined
Sphinx Documentation subprocess failed with return code 1
```

**Comment by bsipocz** [comment]
Closing as this is not an `astropy-helpers` issue but one of `sphinx-gallery`. See  https://github.com/sphinx-gallery/sphinx-gallery/issues/241

I suggest to stick with sphinx <1.6 for now. A workaround is already been placed into our CI so this is not expected to raise any issues on travis runs that use ``ci-helpers``:   https://github.com/astropy/ci-helpers/pull/190

**Comment by cczhu** [comment]
Thanks for your help!  Will stick to sphinx 1.5.6 for now.

**Comment by bsipocz** [comment]
Oh, wait a minute. This is the same issue we saw for ``sphinx-gallery``, but you're right that it comes from ``automodapi``. Those extensions are being moved to a separate package https://github.com/astropy/sphinx-automodapi very recently, so I suggest to reopen the issue in that repository.
