### ISSUE TITLE
Running setup.py in affiliated package is not possible unless numpy is already installed

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy-helpers#402]
In a clean environment, running `setup.py` in any affiliated package will cause something like the error listed below. This is obviously unintuitive and undesirable behavior. 

**EDIT**: This apparently only affects `setup.py install/develop`, but not `setup.py egg_info`, which is why it has not been detected in Astropy's CI builds.

It's not yet clear to me yet whether this can be fixed by putting some `try/except` logic around the imports below (and possibly elsewhere), or whether this is a more fundamental problem with the helpers strategy: https://github.com/astropy/astropy-helpers/blob/e2b5151a33f1aafa0a19134c76d0ec9eb9d75221/astropy_helpers/utils.py#L59-L79

```
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 143, in <module>
    **package_info
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/site-packages/setuptools/command/develop.py", line 138, in install_for_development
    self.run_command('build_ext')
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/ddavella/miniconda3/envs/ah-bottleneck/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ddavella/sandbox/ah-bottleneck/astropy_helpers/astropy_helpers/commands/build_ext.py", line 292, in run
    np_include = get_numpy_include_path()
  File "/Users/ddavella/sandbox/ah-bottleneck/astropy_helpers/astropy_helpers/utils.py", line 72, in get_numpy_include_path
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by astrofrog** [comment]
Normally the way this should work is that if numpy is in ``install_requires``, and if affiliated packages specify the include path as ``'numpy'`` then we'd avoid this - but maybe something has changed recently in setuptools?

**Comment by astrofrog** [comment]
The proper solution is of course https://github.com/astropy/astropy-helpers/issues/334 but I think it might still be a while until we can rely on that.

**Comment by drdavella** [comment]
@astrofrog this problem occurs even if `numpy` is in `install_requires`.

**Comment by saimn** [comment]
numpy should be in `setup_requires` I think.

**Comment by saimn** [comment]
`install_requires` is just the runtime dependencies.

**Comment by drdavella** [comment]
@saimn then this should be part of the package template, but it is not currently.

**Comment by saimn** [comment]
@drdavella - probably because it is useful only if you build a C/Cython extension using Numpy. But it could be mentioned somewhere.

**Comment by drdavella** [comment]
@saimn I'm not sure that's true. This issue occurs for me with a new package created from cookiecutter that does not have any C extensions.

**Comment by bsipocz** [comment]
>  I'm not sure that's true. This issue occurs for me with a new package created from cookiecutter that does not have any C extensions.

there may be still tons of issues with the cookiecutter, so issues and especially PRs are very much welcome for the template.

**Comment by drdavella** [comment]
@bsipocz I think the change here means no change in `cookiecutter` is needed right now. But I'll keep that in mind for future issues.
