### ISSUE TITLE
Running setup.py modifies __NUMPY_SETUP__ to the detriment of other dependencies

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy-helpers#403]
When an affiliated package runs `setup.py`, helpers destructively modifies `builtins.__NUMPY_SETUP__`. 

The problem is that other dependencies (e.g. [bottleneck](https://github.com/kwgoodman/bottleneck)) may try to check `__NUMPY_SETUP__` in their `setup.py`. In the case of `bottleneck` specifically, the check fails with an exception since `builtins.__NUMPY_SETUP__` has been deleted by `astropy-helpers`, and so the entire setup fails.

To test this, it is enough to create a new package using the package template and to add a single dependency of `bottleneck` in `install_requires`. It will fail with something like the following error:

```
Processing dependencies for mosviz==0.2.0.dev532
Searching for bottleneck>=1.2
Reading https://pypi.org/simple/bottleneck/
Downloading https://files.pythonhosted.org/packages/05/ae/cedf5323f398ab4e4ff92d6c431a3e1c6a186f9b41ab3e8258dff786a290/Bottleneck-1.2.1.tar.gz#sha256=6efcde5f830aed64feafca0359b51db0e184c72af8ba6675b4a99f263922eb36
Best match: Bottleneck 1.2.1
Processing Bottleneck-1.2.1.tar.gz
Writing /var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/setup.cfg
Running Bottleneck-1.2.1/setup.py -q bdist_egg --dist-dir /var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/egg-dist-tmp-s7ik4nuz
Traceback (most recent call last):
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/setup.py", line 110, in <module>
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 295, in run
    self.find_sources()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 302, in find_sources
    mm.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 533, in run
    self.add_defaults()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 569, in add_defaults
    sdist.add_defaults(self)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/setup.py", line 24, in finalize_options
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 148, in <module>
    **package_info
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 415, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
    return self.obtain(req, installer)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
    return installer(requirement)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 676, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 887, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1155, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1141, in run_setup
    run_setup(setup_script, args)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/setup.py", line 110, in <module>
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 295, in run
    self.find_sources()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 302, in find_sources
    mm.run()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 533, in run
    self.add_defaults()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 569, in add_defaults
    sdist.add_defaults(self)
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/mfix/anaconda3/envs/mosviz_dev_env/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/var/folders/lj/2z8rzkds0jl__cpf16jg7ssr0001k4/T/easy_install-wvpok8zc/Bottleneck-1.2.1/setup.py", line 24, in finalize_options
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

**Comment by saimn** [comment]
Numpy deletes this variable since v1.12 (https://github.com/numpy/numpy/commit/bbee747c4d53232e5e12a56cc22d7e2365a9d162), so I guess this could now be removed.
(And bottleneck should use a more robust way for checking this!)

**Comment by drdavella** [comment]
@saimn that's useful to know, but it doesn't explain why this issue occurs. I think there's something more subtle going on but I need to dig a little deeper.
