### ISSUE TITLE
setup.py broken?

### ISSUE THREAD

**Issue by juliotux** [astropy/astropy-helpers#505]
I don't know exactly why, but `astropy_helpers` present the same problem when installing via `pip` or `ah_bootstrap.py`. I tried manual install and got these results for release and git versions:

```
pip install astropy_helpers
Collecting astropy_helpers
  Downloading https://files.pythonhosted.org/packages/57/f1/9b11cbda11f320db80fba7e0c4a54d70d38eb3370bfec99ae22232df88c4/astropy-helpers-4.0.tar.gz (52kB)
     |████████████████████████████████| 61kB 1.1MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/julio/anaconda3/bin/python /home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_dsc6wbh
       cwd: /tmp/pip-install-y0gan_5f/astropy-helpers
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-z9riqrie/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-z9riqrie/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-z9riqrie/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 17, in <module>
      from astropy_helpers.version_helpers import generate_version_py  # noqa
  ModuleNotFoundError: No module named 'astropy_helpers'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/julio/anaconda3/bin/python /home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_dsc6wbh Check the logs for full command output.
```

```
pip install https://github.com/astropy/astropy-helpers/archive/master.zip
Collecting https://github.com/astropy/astropy-helpers/archive/master.zip
  Downloading https://github.com/astropy/astropy-helpers/archive/master.zip
     - 419kB 1.4MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/julio/anaconda3/bin/python /home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpx1ko2cqr
       cwd: /tmp/pip-req-build-bmi_h_lu
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-in7fm44q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-in7fm44q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-in7fm44q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 17, in <module>
      from astropy_helpers.version_helpers import generate_version_py  # noqa
  ModuleNotFoundError: No module named 'astropy_helpers'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/julio/anaconda3/bin/python /home/julio/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpx1ko2cqr Check the logs for full command output.
```

This also broke my [CI](https://travis-ci.org/juliotux/astropop/jobs/624859751) today.

**Comment by astrofrog** [comment]
I think I know how to fix this - fix coming shortly
